apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: aspcorealpine-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: aspcorealpine
  template:
    metadata:
      labels:
        app: aspcorealpine
    spec:
      containers:
      - name: aspcorealpine-container
        image: "dtr.dckr.it/pdebruin/aspcorealpine:238"
        ports:
        - containerPort: 80