apiVersion: v1
kind: Pod
metadata:
 name: aspcorealpine
 labels:
   app: aspcorealpine
spec:
 containers:
 - name: aspcorealpine-container
   image: "dtr.dckr.it/pdebruin/aspcorealpine"
   ports:
   - containerPort: 80