apiVersion: v1
kind: Service
metadata:
  name: aspcorealpine-service
  labels:
   app: aspcorealpine-service
spec:
  selector:
    app: aspcorealpine
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: LoadBalancer
