on: [push]

jobs:
  build:
    runs-on: ubuntu-16.04 #ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/container-actions/docker-login@master
      with:
        login-server: pieterd.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    
    - run: |
        docker build . -t pieterd.azurecr.io/pdebruin/aspcorealpine:${{ github.sha }}
        docker push pieterd.azurecr.io/pdebruin/aspcorealpine:${{ github.sha }}
      
    # Set the target AKS cluster. 
    - uses: azure/k8s-actions/aks-set-context@master
      with:
        creds: '${{ secrets.AZURE_CREDENTIALS }}'
        cluster-name: aks201907
        resource-group: aksrg201907
        
    - uses: azure/k8s-actions/k8s-create-secret@master
      with:
        container-registry-url: pieterd.azurecr.io
        container-registry-username: ${{ secrets.REGISTRY_USERNAME }}
        container-registry-password: ${{ secrets.REGISTRY_PASSWORD }}
        secret-name: demo-k8s-secret

    - uses: azure/k8s-actions/k8s-deploy@master
      with:
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          pieterd.azurecr.io/pdebruin/aspcorealpine:${{ github.sha }}
        imagepullsecrets: |
          demo-k8s-secret
